import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Routing Next Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body>
      <header className="bg-blue-500 p-4">
        Header
      </header>
     
        {children}
      
      <footer className="bg-yellow-500 p-4">
        Footer
      </footer>
      </body>
    </html>
   
  );
}
